# Generated by Django 4.1 on 2023-05-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthplatform', '0004_alter_customuser_dob_alter_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='problem_statement',
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthplatform.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthplatform.doctor')),
            ],
        ),
    ]
