# Generated by Django 4.2.1 on 2023-05-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthplatform', '0006_alter_customuser_dob_alter_review_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
